import { Inter } from "next/font/google";
import "./globals.css";
import useServerDarkMode from "@/hooks/useServerDarkMode";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    template: "%s | Finance App",
    default: "Finance App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = useServerDarkMode();
  return (
    <html lang="en" className={`${theme}`}>
      <body className={`${inter.className} min-h-screen antialiased flex flex-col px-8`}>{children}</body>
    </html>
  );
}
